# Inspiration from:
# - https://cristianadam.eu/20191222/using-github-actions-with-c-plus-plus-and-cmake/
# - https://github.com/cristianadam/HelloWorld/blob/master/.github/workflows/build_cmake.yml
# - https://github.com/marketplace/actions/vcpkg-action

name: GH Debug

on:
  workflow_dispatch: {} # allow running it manually
  push:
    branches:
      - main
    tags:
      - v**
  pull_request:
    branches:
      - main
    tags:
      - v**

env:
  BUILD_TYPE: Coverage

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Windows Latest MSVC", ext: "windows-msvc",
            os: windows-latest,
            cc: "cl", cxx: "cl",
            environment_script: "C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Auxiliary/Build/vcvars64.bat",
            vcpkg_triplet: x64-windows
          }
        # - {
        #     name: "Windows Latest MinGW", ext: "windows-mingw",
        #     os: windows-latest,
        #     cc: "gcc", cxx: "g++",
        #     vcpkg_triplet: x64-mingw-dynamic
        #   }
        - {
            name: "Ubuntu Latest GCC", ext: "linux",
            os: ubuntu-latest,
            cc: "gcc", cxx: "g++",
            vcpkg_triplet: x64-linux
          }
        - {
            name: "macOS Latest Clang", ext: "macos",
            os: macos-latest,
            cc: "clang", cxx: "clang++",
            vcpkg_triplet: x64-osx
          }

    defaults:
      run:
        # Run scripts with project directory as working directory
        working-directory: ./
        # Use bash as default shell
        shell: bash

    steps:
    - uses: actions/checkout@v3
      with:
        path: project

    - name: Install Ninja
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then
          sudo apt-get install -y ninja-build
        elif [ "$RUNNER_OS" == "Windows" ]; then
          choco install ninja
        elif [ "$RUNNER_OS" == "macOS" ]; then
          brew install ninja
        fi

    - name: Install ccache
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then
          sudo apt-get install -y ccache
        elif [ "$RUNNER_OS" == "Windows" ]; then
          choco install ccache
        elif [ "$RUNNER_OS" == "macOS" ]; then
          brew install ccache
        fi

    - name: Install code coverage tool
      if: runner.os == 'Windows'
      run: choco install opencppcoverage

    # vcpkg is too slow and it's giving problems on Linux, so we use it
    # only for Windows
    - name: Install dependencies
      if: runner.os != 'Windows'
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then
          sudo apt-get install -y libwxgtk3.0-gtk3-dev libgtest-dev
        elif [ "$RUNNER_OS" == "macOS" ]; then
          brew install wxwidgets googletest
        fi

    # - name: Install Ubuntu dependencies for vcpkg packages
    #   if: runner.os == 'Linux'
    #   run: |
    #     sudo apt-get install -y libx11-dev libxft-dev libxext-dev libwayland-dev \
    #       libxkbcommon-dev libegl1-mesa-dev libibus-1.0-dev \
    #       libdbus-1-dev libxi-dev libxtst-dev

    - name: vcpkg
      id: vcpkg
      if: runner.os == 'Windows'
      uses: johnwason/vcpkg-action@master
      env:
        # Because we have the vcpkg.json file but don't use it, we must turn manifest mode off
        VCPKG_MANIFEST_MODE: OFF
      with:
        # Manifest builds on every CMake configure, which is not acceptable
        #manifest-dir: ${{ github.workspace }}
        pkgs: wxwidgets gtest
        triplet: ${{ matrix.config.vcpkg_triplet }}
        cache-key: ${{ matrix.config.ext }}
        revision: master
        token: ${{ github.token }}

    - name: Prepare ccache timestamp
      id: ccache_cache_timestamp
      shell: cmake -P {0}
      run: |
        string(TIMESTAMP current_date "%Y-%m-%d-%H;%M;%S" UTC)
        file(APPEND "$ENV{GITHUB_OUTPUT}" "timestamp=${current_date}")

    - name: ccache cache files
      uses: actions/cache@v3.2.1
      with:
        path: .ccache
        key: ${{ matrix.config.name }}-ccache-${{ steps.ccache_cache_timestamp.outputs.timestamp }}
        restore-keys: |
          ${{ matrix.config.name }}-ccache-

    - name: Configure
      env:
        CC: ${{ matrix.config.cc }}
        CXX: ${{ matrix.config.cxx }}
        ENVIRONMENT_SCRIPT: ${{ matrix.config.environment_script }}
        RUNNER_OS: ${{ runner.os }}
        VCPKG_TRIPLET: ${{ matrix.config.vcpkg_triplet }}
      working-directory: project
      run: |
        chmod a+x ./.github/scripts/*.cmake
        cmake -P ./.github/scripts/configure.cmake

    - name: Build
      env:
        CXX: ${{ matrix.config.cxx }}
        ENVIRONMENT_SCRIPT: ${{ matrix.config.environment_script }}
        RUNNER_OS: ${{ runner.os }}
      working-directory: project
      run: |
        cmake -P ./.github/scripts/build.cmake

    - name: ccache statistics
      shell: cmake -P {0}
      run: |
        file(TO_CMAKE_PATH "$ENV{GITHUB_WORKSPACE}" ccache_basedir)
        set(ENV{CCACHE_BASEDIR} "${ccache_basedir}")
        set(ENV{CCACHE_DIR} "${ccache_basedir}/.ccache")

        execute_process(COMMAND ccache -s)

    - name: Run tests
      working-directory: project
      run: cmake -P ./.github/scripts/test.cmake

    - name: Install Strip
      working-directory: project
      run: cmake --install build --prefix instdir --strip --config $BUILD_TYPE
