name: Clear all Github actions caches
on:
  # schedule to clear on sundays
  #schedule:
  #  - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  my-job:
    name: Delete all caches
    runs-on: ubuntu-20.04

    steps:
      - name: Clear caches
        uses: easimon/wipe-cache@main